### ISSUE TITLE
Crashing on start (2.1-alpha3)

### ISSUE THREAD

**Issue by AndiDink00x** [abh80/smart-edge#13]
App (2.1-alpha3) instantly crashes when starting on my Poco X3 Pro with the latest build of LineageOS 19.1 rom 

Very nice app and the only one on F-Droid implementing the dynamic island notification.

**Comment by abh80** [comment]
This will be fixed on new release

**Comment by AndiDink00x** [comment]
Fixed in alpha 4!q
