### ISSUE TITLE
This is also a Problem Plz. Fixed it

### ISSUE THREAD

**Issue by AppisGame** [abh80/smart-edge#20]
I have Realme 8 Mobile for testing front camera on left hand side notification icon is hide under the camera.
![1](https://user-images.githubusercontent.com/115078177/194367145-a05384de-05ae-48f9-885b-498479770fbf.jpg)
![2](https://user-images.githubusercontent.com/115078177/194367153-54e2b1db-1996-467a-9452-312115072cd9.jpg)

**Comment by abh80** [comment]
This is work in progress as notes in #8

**Comment by AppisGame** [comment]
when long press on Dynamic Island it comes Wrong if i change the position of Dynamic.

**Comment by AppisGame** [comment]
ok

**Comment by abh80** [comment]
@AppisGame this has been fixed in new release
