### ISSUE TITLE
Crash right after enabling on pixel 6

### ISSUE THREAD

**Issue by walkrr** [abh80/smart-edge#23]
[com.abh80.smartedge.activities.MainActivity$ItemDecoration.onDraw(MainActivity.java:261), androidx.recyclerview.widget.RecyclerView.onDraw(RecyclerView.java:4494), android.view.View.draw(View.java:23195), androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429), android.view.View.updateDisplayListIfDirty(View.java:22062), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513), android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486), android.view.View.updateDisplayListIfDirty(View.java:22018), android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682), android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688), android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786), android.view.ViewRootImpl.draw(ViewRootImpl.java:4579), android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290), android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517), android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286), android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948), android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231), android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239), android.view.Choreographer.doCallbacks(Choreographer.java:899), android.view.Choreographer.doFrame(Choreographer.java:832), android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214), android.os.Handler.handleCallback(Handler.java:942), android.os.Handler.dispatchMessage(Handler.java:99), android.os.Looper.loopOnce(Looper.java:201), android.os.Looper.loop(Looper.java:288), android.app.ActivityThread.main(ActivityThread.java:7898), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)]

**Comment by abh80** [comment]
closed with #21
