### ISSUE TITLE
SongVisualizer: missing for some devices

### ISSUE THREAD

**Issue by abh80** [abh80/smart-edge#3]
I've noticed that the animation is missing for this screen size

![Capture](https://user-images.githubusercontent.com/33550926/193292443-097fc7f1-e8c8-43e6-85ac-aa5e01bb605c.PNG)

_Originally posted by @abdelmohcen in https://github.com/abh80/smart-edge/issues/1#issuecomment-1263651539_

**Comment by abh80** [comment]
Looks like it only occurs when using soundcloud, i will check upon it

**Comment by abdelmohcen** [comment]
> Looks like it only occurs when using soundcloud, i will check upon it

okay thank you

**Comment by Lavin-tom** [comment]
Visualizer missing while using [ViMusic ](https://github.com/vfsfitvnm/ViMusic)  too

**Comment by abh80** [comment]
solution same as #26
