### ISSUE TITLE
Ability to fine-tune postion/size

### ISSUE THREAD

**Issue by Tigriz** [abh80/smart-edge#39]
In dynamicSpot, you have the possibility to adjust the size/position of dynamic island pixel by pixel thanks to buttons and not only slider and know the actual value of it.
It would be nice to have this in Smart Edge, where it's difficult to have the pixel perfect size with the slider only.

e.g. dynamicSpot
![dynamicSpot settings](https://i.imgur.com/BOBIS6Q.jpg)

**Comment by abh80** [comment]
Fixed in new version
