### ISSUE TITLE
Preview doesn't show correctly

### ISSUE THREAD

**Issue by olik09** [abh80/smart-edge#41]
It's lovely, however, I have one probably. I have two selfie cams on the left edge of my screen, so I moved the dynamic island to the left covering the two cams and it looks brilliant but when I long press, the preview won't show correctly. Half of it is hidden.
![Screenshot_20221009-214156_1](https://user-images.githubusercontent.com/64234041/194774136-62af5b4b-83ab-49f4-a3f0-2965bd74ef3d.png)

**Comment by abh80** [comment]
This is now fixed in latest release
