### ISSUE TITLE
issues in new update 

### ISSUE THREAD

**Issue by mukeshwebs** [abh80/smart-edge#5]
1. Previously on clicking the dynamic island it zooms and displays to play, pause and forward and now in latest update while playing music and clicking on dynamic island it does not creates the zoom view.
2. if we don't do any activity like playing music and click on dynamic island it doesn't show anything you can try adding things in this condition with image attached.

![image](https://user-images.githubusercontent.com/53649320/193384867-e08e6f7c-9179-4947-8dac-16d340f6ef6d.png)

if user click on dynamic island and no music is playing or no active notification are there then u can display as displayed in image.

**Comment by abh80** [comment]
Sorry, i didn't tell you that now you have to **long press** the island to open and **slide up or touch outside** to close the island.

**Comment by abh80** [comment]
I will consider adding what you told in 2nd point, thanks for the tip

**Comment by abh80** [comment]
Can be closed now

**Comment by mukeshwebs** [comment]
Thanks
