### ISSUE TITLE
new issue in current release

### ISSUE THREAD

**Issue by mukeshwebs** [abh80/smart-edge#6]
1. dynamic island disappears after receiving 2-3 notifications

**Comment by abh80** [comment]
Yes I am working on it

**Comment by mukeshwebs** [comment]
cool

**Comment by abh80** [comment]
@mukeshwebs I am starting build please check for bugs

**Comment by mukeshwebs** [comment]
ok notify me once after it is released

**Comment by abh80** [comment]
Its done

**Comment by mukeshwebs** [comment]
k checking

**Comment by mukeshwebs** [comment]
it works fine but needs improvement mentioned areas
1. add height and width adjustment of dynamic island
2. positioning of dynamic island on different places in screen

**Comment by abh80** [comment]
yes i am working on that after auto updater

**Comment by abh80** [comment]
context of this issue is solved so i will close it now

**Comment by mukeshwebs** [comment]
🤩
