### ISSUE TITLE
please increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [abh80/smart-edge#7]
While there are already 5 releases listed, the APK at the last one still identifies with `versionCode: 1`. As `versionCode` is used by Android internally to keep versions apart, it would not consider newer releases as newer versions, and thus not consider them for update.

Can you please increase this integer with each new release? How much is up to you as long as the new one is higher (some use it as "release counter", others prefer a timestamp or have the `versionName` reflected e.g. by a calculation like `major * 10000 + minor * 100 + patch`, ie. `20103` for a v2.1.3). Thanks in advance!

**Comment by abh80** [comment]
Thank you for bringing it, I have started to update versionCode but its not pushed right now as I am working on auto update.

I will definitely consider your method next time

**Comment by IzzySoft** [comment]
Thanks! Looks good :smiley: [See here](https://apt.izzysoft.de/fdroid/index/apk/com.abh80.smartedge) after 6 pm UTC today (corrections/updates to the description etc welcome if any).

**Comment by abh80** [comment]
Can you please update the description to `Alternative to dynamic island for android.`? 
Thanks

**Comment by IzzySoft** [comment]
Can do, though it's obvious that it's for Android as this is a repo for Android apps only. But by your request a final piece of the puzzle falls into place: *Smart Edge* is to Android what "Dynamic Island" is to iOS, right? So maybe use that phrase instead?

> *Smart Edge* is to Android what "Dynamic Island" is to iOS: it shows your music status under the pinhole camera.

Going by the screenshots it seems one can expand it (it shows minimized by default but the user can expand it for details). So maybe for those not familiar with it, the description could be expanded with some additional details?

> *Smart Edge* is to Android what "Dynamic Island" is to iOS: it shows your music status under the pinhole camera. Like *Dynamic Island,* it "hides" the camera and other sensors sitting in the "notch" – but no longer as a simple "black bar". Instead it gives you a basic status of the music playing: a minimized cover and a minimized sound graph. Tapping it will expand it to a 4x2 element looking similar to the music information on the lock screen or in the expanded notification bar and lets you interact with the music player to e.g. pause the music or skip to the next/previous title in your play list.

Did I get that right? Shall I use that instead (maybe with some adjustments of yours)?
